export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL'

export const TASK_GET_REQUEST = 'TASK_GET_REQUEST'
export const TASK_GET_SUCCESS = 'TASK_GET_SUCCESS'
export const TASK_GET_FAIL = 'TASK_GET_FAIL'

export const TASK_EDIT_REQUEST = 'TASK_EDIT_REQUEST'
export const TASK_EDIT_SUCCESS = 'TASK_EDIT_SUCCESS'
export const TASK_EDIT_FAIL = 'TASK_EDIT_FAIL'

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_REQUEST'
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS'
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL'

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL'

export const TASK_PRIORITY_FAIL = 'TASK_PRIORITY_FAIL'



